[package]
name = "dioxus"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
dioxus = { version = "0.5", features = ["hooks"] }
dioxus-desktop = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
